### ISSUE TITLE
Problem with python manage.py migrate

### ISSUE THREAD

**Issue by luisbauti92** [onaio/onadata#1699]
S.O: **Linux Mint 19**
**Python 3.6**

I have a error, when try run the command 'make'

```
python manage.py migrate
Your environment is:"onadata.settings.common"
Traceback (most recent call last):
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/rest_framework/settings.py", line 183, in import_from_string
    module = import_module(module_path)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/labautistab/Desarrollo/onadata/onadata/libs/authentication.py", line 18, in <module>
    from multidb.pinning import use_master
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/src/django-multidb-router/multidb/__init__.py", line 43, in <module>
    if getattr(settings, 'SLAVE_DATABASES'):
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/conf/__init__.py", line 58, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'SLAVE_DATABASES'
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/labautistab/Desarrollo/onadata/onadata/apps/main/urls.py", line 12, in <module>
    from onadata.apps.api.urls import router
  File "/home/labautistab/Desarrollo/onadata/onadata/apps/api/urls.py", line 7, in <module>
    from rest_framework import routers
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/rest_framework/routers.py", line 28, in <module>
    from rest_framework import (
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/rest_framework/views.py", line 19, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/rest_framework/schemas/__init__.py", line 32, in <module>
    authentication_classes=api_settings.DEFAULT_AUTHENTICATION_CLASSES,
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/rest_framework/settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/rest_framework/settings.py", line 172, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/rest_framework/settings.py", line 172, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/home/labautistab/Desarrollo/onadata/.virtualenv/lib/python3.6/site-packages/rest_framework/settings.py", line 187, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'onadata.libs.authentication.DigestAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. AttributeError: 'Settings' object has no attribute 'SLAVE_DATABASES'.
```
Makefile:2: recipe for target 'blank' failed
make: *** [blank] Error 1

Any idea why it's wrong?

**Comment by DavisRayM** [comment]
Do you have a `local_settings.py` file ? If not try running `cp onadata/settings/default_settings.py onadata/settings/local_settings.py` and retry the migrate

**Comment by DavisRayM** [comment]
@luisbauti92 Hope the above solution worked for you. I'm going to be closing this issue, feel free to ask if you require any more assistance.

**Comment by tymiles003** [comment]
Team, 
I have the same error, what was the solution for this error?

**Comment by hermanmaraden** [comment]
> @luisbauti92 Hope the above solution worked for you. I'm going to be closing this issue, feel free to ask if you require any more assistance.




> `cp onadata/settings/default_settings.py onadata/settings/local_settings.py`


Pardon me, I also have same problem when installing onadata.io. I have copied the local_setings.py but still not success. Could you give me a solution based on this problem?

**Comment by DavisRayM** [comment]
Hey @hermanmaraden, kindly try:

- Running onadata with `python manage.py runserver --settings=onadata.settings.local_settings` or exporting `DJANGO_SETTINGS_MODULE=onadata.settings.local_settings`
- Adding `SLAVE_DATABASES = []` in your settings

**Comment by hermanmaraden** [comment]
> Hey @hermanmaraden, kindly try:
> 
> * Running onadata with `python manage.py runserver --settings=onadata.settings.local_settings` or exporting `DJANGO_SETTINGS_MODULE=onadata.settings.local_settings`
> * Adding `SLAVE_DATABASES = []` in your settings

Thank you so much for your help. That solved the problems.

**Comment by hermanmaraden** [comment]
> Hey @hermanmaraden, kindly try:
> 
> * Running onadata with `python manage.py runserver --settings=onadata.settings.local_settings` or exporting `DJANGO_SETTINGS_MODULE=onadata.settings.local_settings`
> * Adding `SLAVE_DATABASES = []` in your settings
Pardon me if I ask again. I got this error when running python3 manage.py runserver --nothreading 
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.

What is the solution of this? Should I change ALLOWED_HOSTS in local_settings.py to IP address?

**Comment by hermanmaraden** [comment]
> Hey @hermanmaraden, kindly try:
> 
> * Running onadata with `python manage.py runserver --settings=onadata.settings.local_settings` or exporting `DJANGO_SETTINGS_MODULE=onadata.settings.local_settings`
> * Adding `SLAVE_DATABASES = []` in your settings



Pardon me if I ask again. I got this error when running python3 manage.py runserver --nothreading
CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.
What is the solution of this? Should I change ALLOWED_HOSTS in local_settings.py to IP address?

**Comment by DavisRayM** [comment]
@hermanmaraden Yes you'll either need to set `ALLOWED_HOSTS` to a list of IPs you'd like to allow (or allow all IPs `ALLOWED_HOSTS = [*]`); This is if you'd like to run the application without `DEBUG` set to `true`

**Comment by hermanmaraden** [comment]
Pardon me, I have tried 
from onadata.settings.staging_example import *  # noqa

DEBUG = True
ALLOWED_HOSTS = ["*"]

And also 

from onadata.settings.staging_example import *  # noqa

DEBUG = True
ALLOWED_HOSTS = ["192.168.43.208","127.0.0.1","localhost"]

but still no success. What is wrong with my settings there?

**Comment by DavisRayM** [comment]
> Pardon me, I have tried
> from onadata.settings.staging_example import * # noqa
> 
> DEBUG = True
> ALLOWED_HOSTS = ["*"]
> 
> And also
> 
> from onadata.settings.staging_example import * # noqa
> 
> DEBUG = True
> ALLOWED_HOSTS = ["192.168.43.208","127.0.0.1","localhost"]
> 
> but still no success. What is wrong with my settings there?

Nothing is wrong with your settings in both cases as far as I can see. For the changes to take effect you need to specify the setting to use `python manage.py runserver --nothreading --settings=onadata.settings.local_settings`.

_You can also move the `local_settings` to the root directory of the project along side the `manage.py` file and the application will automatically load the settings`

**Comment by hermanmaraden** [comment]
Thank you so much again. I finally can run the onadata.io. But how can I access it? I have tried it using browser using my local IP but it is said that it cannot be reached. What should I do? Can I run this onadata.io and access it from local intranet?

**Comment by hermanmaraden** [comment]
> Thank you so much again. I finally can run the onadata.io. But how can I access it? I have tried it using browser using my local IP but it is said that it cannot be reached. What should I do? Can I run this onadata.io and access it from local intranet?

For this trial I am using virtual box running on my laptop. I can access the Postgresql DB from using the local IP. And I can run ssh to test the virtual box machine. But I cannot access the onadata.io page by using the local IP address.

**Comment by hermanmaraden** [comment]
Finally I can run and access the local onadata.io by running 

sudo python3 manage.py runserver --nothreading --settings=onadata.settings.local_settings 0.0.0.0:8000

But I have another question, does this local onadata.io have submission limitation like in onadata.io cloud? Because we try to make our own local onadata.io because of there is submission limitation in cloud system.

**Comment by hermanmaraden** [comment]
> 
> 
> > Pardon me, I have tried
> > from onadata.settings.staging_example import * # noqa
> > DEBUG = True
> > ALLOWED_HOSTS = ["*"]
> > And also
> > from onadata.settings.staging_example import * # noqa
> > DEBUG = True
> > ALLOWED_HOSTS = ["192.168.43.208","127.0.0.1","localhost"]
> > but still no success. What is wrong with my settings there?
> 
> Nothing is wrong with your settings in both cases as far as I can see. For the changes to take effect you need to specify the setting to use `python manage.py runserver --nothreading --settings=onadata.settings.local_settings`.
> 
> _You can also move the `local_settings` to the root directory of the project along side the `manage.py` file and the application will automatically load the settings_

Pardon me Davis if I ask you again. I have installed it and can run it. But somehow I was trying to upload XLSForm but the process was never completed. I have followed the installation instructions until **copy static files to static dir**. Should I continue until **setup nginx** for intranet onadata?
