### ISSUE TITLE
Error message returned while installing Onadata

### ISSUE THREAD

**Issue by Janemesi** [onaio/onadata#1851]
Environmental Information

- Operating System: ubuntu 18.04
- Onadata version: 
- Python version: 3.7.8

Problem description
A user is encountering an error message while installing Onadata:
python manage.py migrate
Your environment is:"onadata.settings.common"
Traceback (most recent call last):
File "manage.py", line 21, in <module>
execute_from_command_line(sys.argv)
File "/srv/onadata/virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/srv/onadata/virtualenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
django.setup()
File "/srv/onadata/virtualenv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/srv/onadata/virtualenv/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
app_config.ready()
File "/srv/onadata/onadata/apps/messaging/apps.py", line 18, in ready
from onadata.apps.messaging import signals # noqa pylint: disable=W0612
File "/srv/onadata/onadata/apps/messaging/signals.py", line 12, in <module>
from onadata.apps.messaging.backends.base import call_backend
File "/srv/onadata/onadata/apps/messaging/backends/base.py", line 10, in <module>
from multidb.pinning import use_master
File "/srv/onadata/virtualenv/src/django-multidb-router/multidb/__init__.py", line 43, in <module>
if getattr(settings, 'SLAVE_DATABASES'):
File "/srv/onadata/virtualenv/lib/python3.7/site-packages/django/conf/__init__.py", line 80, in __getattr__
val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'SLAVE_DATABASES'
Makefile:2: recipe for target 'blank' failed
make: *** [blank] Error 1

Additional Information
The steps taken before encountering the error message:

1. clone the repository: git clone https://github.com/onaio/onadata.git

2. useradd -m onadata -G www-data

3. sudo mv onadata /srv/onadata
4. sudo chown -R onadata:www-data /srv/onadata/

5. cd /srv/onadata

6. ran the script: ./script/install/ubuntu

7. then created the database:

sudo su postgres -c "psql -c \"CREATE USER onadata WITH PASSWORD 'onadata';\""
sudo su postgres -c "psql -c \"CREATE DATABASE onadata OWNER onadata;\""
sudo su postgres -c "psql -d onadata -c \"CREATE EXTENSION IF NOT EXISTS postgis;\""
sudo su postgres -c "psql -d onadata -c \"CREATE EXTENSION IF NOT EXISTS postgis_topology;\""

8. copied the following: cp onadata/settings/default_settings.py onadata/settings/local_settings.py
9. created the virtual environment: virtualenv .virtualenv

10. activated the environment: source .virtualenv/bin/activate

11. ran the pip command: pip-compile --output-file requirements/base.pip requirements/base.in

12. cp pre-commit.sh .git/hooks/pre-commit

13. chmod +x .git/hooks/pre-commit

14. then ran the make command: make

**Comment by WinnyTroy** [comment]
Hi Jane, This issue seems to be that the client is using the common settings file in Onadata, which does not have the database configurations set up.
Kindly instruct the client to update that file in accordance to [this file](https://github.com/onaio/onadata/blob/master/onadata/settings/travis_test.py), dependant on their local database set up or create a local settings file for this and export `DJANGO_SETTINGS_MODULE` to point to this file settings file
