### ISSUE TITLE
Using Docker set up it throws error when loading a new form

### ISSUE THREAD

**Issue by kazlauskis** [onaio/onadata#1865]
### Environmental Information

- Operating System: MacOS Docker
- Onadata version: 2.3.6
- Python version: 3.6

### Problem description

I am sorry if I am missing something obvious. I am trying to spin up the onadata server using the docker-compose instructions. Everything seems fine but I cannot upload any XLS forms using the default web interface. The error says: `invalid literal for int() with base 10: '9-internal'`. This happens with whatever form including the vanilla ONA tutorial one. 

### Expected behavior
Upload the form.

### Steps to reproduce the behavior
Run the server using docker-compose. Create a new account and using the new user account upload a form.

### Additional Information

Thanks!

<img width="517" alt="Screenshot 2020-08-06 at 22 48 09" src="https://user-images.githubusercontent.com/7383162/89586077-ea5cb800-d836-11ea-963d-292bc8ea9efa.png">

``` bash
web_1    | Subject: Form publishing exception: invalid literal for int() with base 10: '9-internal' - d77838dfdae0
web_1    | Message: Exception in request: ValueError: invalid literal for int() with base 10: '9-internal'Traceback (most recent call last):
web_1    |   File "/srv/onadata/onadata/libs/utils/logger_tools.py", line 564, in publish_form
web_1    |     return callback()
web_1    |   File "/srv/onadata/onadata/apps/main/views.py", line 175, in set_form
web_1    |     survey = form.publish(request.user).survey
web_1    |   File "/srv/onadata/onadata/apps/main/forms.py", line 412, in publish
web_1    |     id_string, created_by or user)
web_1    |   File "/usr/lib/python3.6/contextlib.py", line 52, in inner
web_1    |     return func(*args, **kwds)
web_1    |   File "/srv/onadata/onadata/libs/utils/logger_tools.py", line 608, in publish_xls_form
web_1    |     project=project)
web_1    |   File "/srv/onadata/.virtualenv/python3.6/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1    |   File "/srv/onadata/.virtualenv/python3.6/lib/python3.6/site-packages/django/db/models/query.py", line 422, in create
web_1    |     obj.save(force_insert=True, using=self.db)
web_1    |   File "/srv/onadata/onadata/apps/viewer/models/data_dictionary.py", line 198, in save
web_1    |     self.xml = survey.to_xml()
web_1    |   File "/srv/onadata/.virtualenv/python3.6/lib/python3.6/site-packages/pyxform/survey.py", line 955, in to_xml
web_1    |     enketo=enketo,
web_1    |   File "/srv/onadata/.virtualenv/python3.6/lib/python3.6/site-packages/pyxform/survey.py", line 917, in print_xform_to_file
web_1    |     warnings.extend(odk_validate.check_xform(path))
web_1    |   File "/srv/onadata/.virtualenv/python3.6/lib/python3.6/site-packages/pyxform/validators/odk_validate/__init__.py", line 93, in check_xform
web_1    |     check_java_version()
web_1    |   File "/srv/onadata/.virtualenv/python3.6/lib/python3.6/site-packages/pyxform/validators/odk_validate/__init__.py", line 79, in check_java_version
web_1    |     major, minor = int(java_version), 0
web_1    | ValueError: invalid literal for int() with base 10: '9-internal'
```

_Logs, [related issues](github.com/onaio/onadata/issues), weird / out of place occurrences, local settings, possible approach to solving this..._

**Comment by DavisRayM** [comment]
Seems like the `openjdk-9-jre-headless` package isn't compatible with PyXForm.... We'll need to downgrade to `openjdk-8-jre-headless` on the `DockerFile`

@kazlauskis would you like to work on this ?

**Comment by kazlauskis** [comment]
Thanks, I am sorry but, at the moment, I won't have the time to work on this.
