### ISSUE TITLE
Errr running migration

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/onadata#2681]
```
(onadata) onadata:~/app$ python manage.py showmigrations
Your environment is:"onadata.preset.local_settings"
Traceback (most recent call last):
  File "/home/onadata/app-versioned/1724674161/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/django/core/management/commands/showmigrations.py", line 52, in handle
    return self.show_list(connection, options['app_label'])
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/django/core/management/commands/showmigrations.py", line 71, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/django/db/migrations/loader.py", line 214, in build_graph
    self.load_disk()
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/django/db/migrations/loader.py", line 116, in load_disk
    migration_module = import_module(migration_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/taggit/migrations/0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx.py", line 5, in <module>
    class Migration(migrations.Migration):
  File "/home/onadata/.virtualenvs/onadata/lib/python3.10/site-packages/taggit/migrations/0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx.py", line 11, in Migration
    migrations.RenameIndex(
AttributeError: module 'django.db.migrations' has no attribute 'RenameIndex'. Did you mean: 'RemoveIndex'?
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by FrankApiyo** [comment]
This issue is most likely caused by an out of date django version
Check django version by running: `python -m django --version`
