### ISSUE TITLE
SAV Export KeyError exception

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#907]
```python
Exception in request: KeyError: 'super_long_variable_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'Traceback (most recent call last):
  File "/..../app-versioned/1485953010/onadata/apps/viewer/tasks.py", line 293, in create_sav_zip_export
    options
  File "/..../app-versioned/1485953010/onadata/libs/utils/export_tools.py", line 156, in generate_export
    options=options, columns_with_hxl=columns_with_hxl
  File "/..../app-versioned/1485953010/onadata/libs/utils/export_builder.py", line 829, in to_zipped_sav
    sav_writer = SavWriter(sav_file.name, **sav_options)
  File "/..../.virtualenvs/onadata/src/savreaderwriter/savReaderWriter/savWriter.py", line 221, in __init__
    self.valueLabels = valueLabels
  File "/..../.virtualenvs/onadata/src/savreaderwriter/savReaderWriter/header.py", line 300, in valueLabels
    if self.varTypes[varName] == 0:
KeyError: 'super_long_variable_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

**Comment by ukanga** [comment]
It is not necessary limited to a super long variable, seen one with a short key.

**Comment by bmarika** [comment]
Closing this issue as it was not possible to replicate it. The last occurrence was over a year and ago and it could have been fixed. Will reopen the issue should the error surface again.
