### ISSUE TITLE
SAV Export exception ArgumentError: argument 3: <type 'exceptions.TypeError'>: wrong type

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#912]
```python 
Exception in request: ArgumentError: argument 3: <type 'exceptions.TypeError'>: wrong typeTraceback (most recent call last):
  File "/..../app-versioned/1485952384/onadata/apps/viewer/tasks.py", line 293, in create_sav_zip_export
    options
  File "/..../app-versioned/1485952384/onadata/libs/utils/export_tools.py", line 156, in generate_export
    options=options, columns_with_hxl=columns_with_hxl
  File "/..../app-versioned/1485952384/onadata/libs/utils/export_builder.py", line 829, in to_zipped_sav
    sav_writer = SavWriter(sav_file.name, **sav_options)
  File "/..../.virtualenvs/onadata/src/savreaderwriter/savReaderWriter/savWriter.py", line 221, in __init__
    self.valueLabels = valueLabels
  File "/..../.virtualenvs/onadata/src/savreaderwriter/savReaderWriter/header.py", line 302, in valueLabels
    value, c_char_py3k(label))
ArgumentError: argument 3: <type 'exceptions.TypeError'>: wrong type```

**Comment by moshthepitt** [comment]
@ukanga all SAV exceptions are now appropriately caught [here](https://github.com/onaio/onadata/blob/v1.13.0/onadata/libs/utils/export_tools.py#L242) i.e.

```python
    except SPSSIOError as e:
        export = get_or_create_export(export_id, xform, export_type, options)
        export.error_message = str(e)
        export.internal_status = Export.FAILED
        export.save()
        report_exception("SAV Export Failure", e, sys.exc_info())
        return export

```

We unfortunately cannot do more for this issue unless we get the specific form that caused this.
