### ISSUE TITLE
CSV Export: AttributeError: 'NoneType' object has no attribute 'get_abbreviated_xpath'

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#920]
```python
Exception in request: AttributeError: 'NoneType' object has no attribute 'get_abbreviated_xpath'Traceback (most recent call last):
  File "/...../onadata/apps/viewer/tasks.py", line 146, in create_csv_export
    options
  File "/...../onadata/libs/utils/export_tools.py", line 156, in generate_export
    options=options, columns_with_hxl=columns_with_hxl
  File "/...../onadata/libs/utils/export_builder.py", line 703, in to_flat_csv_export
    csv_builder.export_to(path, dataview=dataview)
  File "/...../onadata/libs/utils/csv_builder.py", line 494, in export_to
    data = self._format_for_dataframe(cursor)
  File "/...../onadata/libs/utils/csv_builder.py", line 474, in _format_for_dataframe
    include_images=image_xpaths)
  File "/...../onadata/libs/utils/csv_builder.py", line 364, in _reindex
    item = get_ordered_repeat_value(key, item)
  File "/...../onadata/libs/utils/csv_builder.py", line 342, in get_ordered_repeat_value
    children = data_dictionary.get_child_elements(xpath)
  File "/...../onadata/apps/logger/models/xform.py", line 325, in get_child_elements
    return flatten(element)
  File "/...../onadata/apps/logger/models/xform.py", line 313, in flatten
    xpath = elem.get_abbreviated_xpath()
AttributeError: 'NoneType' object has no attribute 'get_abbreviated_xpath'
```

**Comment by ukanga** [comment]
This might still be an issue, investigate why.
