### ISSUE TITLE
TypeError: must be string, not int on exports string_to_date_with_xls_validation

### ISSUE THREAD

**Issue by ukanga** [onaio/onadata#921]
```python
Exception in request: TypeError: must be string, not intTraceback (most recent call last):
  File "/...../onadata/apps/viewer/tasks.py", line 115, in create_xls_export
    options
  File "/...../onadata/libs/utils/export_tools.py", line 175, in generate_export
    options=options, columns_with_hxl=columns_with_hxl
  File "/...../onadata/libs/utils/export_builder.py", line 671, in to_xls_export
    self.pre_process_row(row, section),
  File "/...../onadata/libs/utils/export_builder.py", line 470, in pre_process_row
    value, elm['type'])
  File "/...../onadata/libs/utils/export_builder.py", line 437, in convert_type
    return func(value)
  File "/...../onadata/libs/utils/export_builder.py", line 190, in <lambda>
    'date': lambda x: ExportBuilder.string_to_date_with_xls_validation(x),
  File "/...../onadata/libs/utils/export_builder.py", line 201, in string_to_date_with_xls_validation
    date_obj = datetime.strptime(date_str, '%Y-%m-%d').date()
TypeError: must be string, not int
```

**Comment by Wambere** [comment]
No longer an issue. 

https://github.com/onaio/onadata/blob/771edf628a1a9cb717ec0b3ead5bb701c06a78c7/onadata/libs/tests/utils/test_export_builder.py#L2135
